name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
            
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: tuxpilgrim/aws-sso-cred-restore:${{ github.ref }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
